version: 2.1
orbs:
  artifactory-orb: jfrog/artifactory-orb@1.0.1
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout

  publish-on-artifactory:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install jFrog CLI
          command: wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.9.0/jfrog-cli-linux-amd64/jfrog

      - run: chmod +x ./jfrog
      - run: gradle build

      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY

      - run: chmod +x gradlew
      
      - run: ./jfrog rt gradle-config --use-wrapper=true --repo-resolve=remote-backend-dev --server-id-resolve=Default-Server --repo-deploy=local-backend-dev --server-id-deploy=Default-Server

      - run: ./jfrog rt bp gradle clean build artifactoryPublish -b build.gradle


workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - sonarCloud
      - publish-on-artifactory:
         requires:
            - build
         filters:
            branches:
              only: main