version: 2.1
orbs:
  artifactory: circleci/artifactory@1.0.0
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout

  publish-on-artifactory:
    docker:
      - image: circleci/circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install jFrog CLI
          command: |
            echo "Checking for existence of CLI"
            set +e
            jfrog -v
            if [ $? -gt 0 ]; then
              echo "Not found, installing latest"
              curl -fL https://getcli.jfrog.io | sh
              chmod a+x jfrog && sudo mv jfrog /usr/local/bin
            else
              echo "CLI exists, skipping install"
            fi
        

      #- run: chmod +x ./jfrog
      #- run: gradle build

      - run: jfrog rt c --user="service-backend" --url="https://sumasaas.jfrog.io/artifactory/" --apikey="AKCp8ihLMESAg4orKmLAikXT7odXVXUqD58eK8nkYV4LrtemKiNpWBnxe1ZB7cnQpMUHssGDC" --interactive=false

      - run: chmod +x gradlew
      
      - run: ./jfrog rt gradle-config --use-wrapper=true --repo-resolve=remote-backend-dev --server-id-resolve=Default-Server --repo-deploy=local-backend-dev --server-id-deploy=Default-Server

      - run: ./jfrog rt bp gradle clean build artifactoryPublish -b build.gradle


workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - sonarCloud
      - publish-on-artifactory:
         requires:
            - build
         filters:
            branches:
              only: main